ladder/urls.py
from django.urls import path

from ladder import views

app_name='ladder'
urlpatterns = [
    # Ladder
    path(r'atual/', views.detalhar_ladder_atual, name='detalhar_ladder_atual'),
    path(r'hall-fama/<int:ano>/<int:indice>/', views.detalhar_hall_fama, name='detalhar_hall_fama'),
    path(r'historico/<int:ano>/<int:mes>/', views.detalhar_ladder_historico, name='detalhar_ladder_historico'),
    path(r'hall-fama/listar/', views.listar_hall_fama, name='listar_hall_fama'),
    path(r'historico/listar/', views.listar_ladder_historico, name='listar_ladder_historico'),
    path(r'atual/listar-desafios/', views.listar_desafios_ladder, name='listar_desafios_ladder_atual'),
    path(r'historico/<int:ano>/<int:mes>/listar-desafios/', views.listar_desafios_ladder, name='listar_desafios_ladder_historico'),
    path(r'hall-fama/<int:ano>/<int:indice>/listar-desafios/', views.listar_desafios_season, name='listar_desafios_season'),
    
    # Remoções
    path(r'cancelar-remocao/<int:remocao_id>/', views.cancelar_remocao_jogador_ladder, name='cancelar_remocao_jogador_ladder'),
    path(r'listar-remocoes/', views.listar_remocoes_jogador_ladder, name='listar_remocoes_jogador_ladder'),
    path(r'remover-jogador/', views.remover_jogador_ladder, name='remover_jogador_ladder'),
    
    # Permissões de aumento de range
    path(r'permissao-aumento-range/adicionar/', views.add_permissao_aumento_range, name='add_permissao_aumento_range'),
    path(r'permissao-aumento-range/remover/', views.remover_permissao_aumento_range, name='remover_permissao_aumento_range'),
    path(r'permissao-aumento-range/remover/<int:permissao_id>/', views.remover_permissao_aumento_range, name='remover_permissao_aumento_range'),
    
    # Desafios de ladder
    path(r'desafio/adicionar/', views.add_desafio_ladder, name='adicionar_desafio_ladder'),
    path(r'desafio/cancelar/<int:desafio_id>/', views.cancelar_desafio_ladder, name='cancelar_desafio_ladder'),
    path(r'desafio/detalhar/<int:desafio_id>/', views.detalhar_desafio_ladder, name='detalhar_desafio_ladder'),
    path(r'desafio/editar/<int:desafio_id>/', views.editar_desafio_ladder, name='editar_desafio_ladder'),
    path(r'desafio/listar-pendentes/', views.listar_desafios_ladder_pendentes_validacao, name='listar_desafios_ladder_pendentes_validacao'),
    path(r'desafio/validar/<int:desafio_id>/', views.validar_desafio_ladder, name='validar_desafio_ladder'),
    
    # Regras
    path(r'regras/', views.detalhar_regras, name='detalhar_regras_ladder'),
    
    # Lutas
    path(r'lutas/detalhar/<int:luta_id>/', views.detalhar_luta, name='detalhar_luta'),
    
    # Análises
    path('analises/geral/', views.analises, name='analises'),
    path('analises/geral/resultado-acumulado-jogadores/', views.analise_resultado_acumulado_jogadores, name='analise_result_acum_jogadores'),
    path('analises/geral/resultado-posicao/', views.analise_resultado_por_posicao, name='analise_resultado_por_posicao'),
    path('analises/geral/resultado-diferenca-posicao/', views.analise_resultado_por_diferenca_posicao, name='analise_resultado_por_diferenca_posicao'),
    path('analises/geral/vitorias-por-personagem/', views.analise_vitorias_por_personagem, name='analise_vitorias_por_personagem'),
    path('analises/jogador/', views.analises_por_jogador, name='analises_por_jogador'),
    path('analises/jogador/resultado-acumulado-jogador/', views.analise_resultado_acumulado_para_um_jogador, name='analise_result_acum_jogador'),
    path('analises/jogador/resultado-contra-personagens-jogador/', views.analise_resultado_acumulado_contra_personagens_para_um_jogador, 
         name='analise_result_jogador_contra_personagens'),
    path('analises/jogador/resultado-stages-jogador/', views.analise_resultado_stages_para_um_jogador, name='analise_stages_jogador'),
    path('analises/jogador/vitorias-desafio/', views.analise_vitorias_desafio_para_um_jogador, name='analise_vitorias_desafio_jogador'),
]

smashLadder/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls.conf import re_path
from django.views.defaults import page_not_found

from ladder.models import Lockdown
from smashLadder import views, settings


urlpatterns = []

# Verificar lockdown de seasons
try:
    if Lockdown.sistema_em_lockdown():
        urlpatterns.append(re_path(r'.*?', page_not_found, {'exception': Exception('Gerando nova Season')}))
except:
    pass
        
urlpatterns.extend([
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', views.home, name='inicio'),
    
    path('jogadores/', include('jogadores.urls.urls_jogadores')),
    path('ladder/', include('ladder.urls')),
    path('personagens/', include('jogadores.urls.urls_personagens')),
    path('stages/', include('jogadores.urls.urls_stages')),
    path('torneios/', include('torneios.urls')),
    path('treinamento/', include('treinamento.urls')),
])

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

ladder/models.py
# -*- coding: utf-8 -*-
"""Modelos usados para ladder"""
import datetime

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone

from configuracao.models import ConfiguracaoLadder
from smashLadder.utils import DateTimeFieldTz


class Luta(models.Model):
    """Registro de uma luta"""
    ganhador = models.ForeignKey('jogadores.Jogador', on_delete=models.CASCADE, related_name='ganhador_luta')
    stage = models.ForeignKey('jogadores.Stage', on_delete=models.CASCADE, blank=True, null=True)
    data = models.DateField(u'Data da luta')
    adicionada_por = models.ForeignKey('jogadores.Jogador', on_delete=models.CASCADE, related_name='criador_luta')
    
    @property
    def ladder(self):
        if hasattr(self, 'lutaladder'):
            return self.lutaladder.ladder
        return None

class JogadorLuta(models.Model):
    """Jogadores participantes de uma luta"""
    jogador = models.ForeignKey('jogadores.Jogador', on_delete=models.CASCADE)
    personagem = models.ForeignKey('jogadores.Personagem', on_delete=models.CASCADE, blank=True, null=True)
    luta = models.ForeignKey('Luta', on_delete=models.CASCADE)
    
    class Meta():
        unique_together = ('jogador', 'luta')
    
class DesafioLadder(models.Model):
    """Desafio para ladder"""
    try:
        LIMITE_POSICOES_DESAFIO = ConfiguracaoLadder.buscar_configuracao([ConfiguracaoLadder.CONFIGURACAO_LIMITE_POSICOES_DESAFIO,]) \
            [ConfiguracaoLadder.CONFIGURACAO_LIMITE_POSICOES_DESAFIO] # Diferença máxima de posições para haver desafio
    except:
        LIMITE_POSICOES_DESAFIO = 3
    
    # É permitido usar coringa na Ladder?
    try:
        USO_CORINGA = ConfiguracaoLadder.buscar_configuracao([ConfiguracaoLadder.CONFIGURACAO_USO_CORINGA,]) \
            [ConfiguracaoLadder.CONFIGURACAO_USO_CORINGA] # Diferença máxima de posições para haver desafio
    except:
        USO_CORINGA = True
    PERIODO_ESPERA_MESMOS_JOGADORES = 3 # Quantidade de dias a esperar para refazer um desafio
    PERIODO_ESPERA_DESAFIO_CORINGA = 60 # Quantidade de dias a esperar para utilizar um coringa
    
    try:
        MELHOR_DE = ConfiguracaoLadder.buscar_configuracao([ConfiguracaoLadder.CONFIGURACAO_MELHOR_DE,]) \
            [ConfiguracaoLadder.CONFIGURACAO_MELHOR_DE] # Quantidade máxima de lutas que um desafio pode ter
    except:
        MELHOR_DE = 3
    SCORE_VITORIA = ((MELHOR_DE // 2) + 1) # Score para vitória
    
    MENSAGEM_ERRO_DESAFIANTE_MUITO_ABAIXO_DESAFIADO = f'Desafiante está mais de {LIMITE_POSICOES_DESAFIO} posições abaixo do desafiado'
    MENSAGEM_ERRO_DESAFIANTE_ACIMA_DESAFIADO = 'Desafiante está à frente do desafiado'
    MENSAGEM_ERRO_MESMO_JOGADOR = 'Desafiante e desafiado não podem ser o mesmo jogador'
    MENSAGEM_ERRO_PERIODO_ESPERA_MESMOS_JOGADORES = f'Desafio não respeita período mínimo de ' \
        f'{PERIODO_ESPERA_MESMOS_JOGADORES} dias entre mesmos jogadores'
    MENSAGEM_ERRO_PERIODO_ESPERA_CORINGA = f'Ainda não acabou o tempo de {PERIODO_ESPERA_DESAFIO_CORINGA} dias '\
        f'para desafiante reutilizar coringa'
    
    desafiante = models.ForeignKey('jogadores.Jogador', on_delete=models.CASCADE, related_name='desafiante')
    desafiado = models.ForeignKey('jogadores.Jogador', on_delete=models.CASCADE, related_name='desafiado')
    desafio_coringa = models.BooleanField(u'É desafio coringa?')
    score_desafiante = models.SmallIntegerField(u'Vitórias do desafiante', validators=[MinValueValidator(0), MaxValueValidator(SCORE_VITORIA)])
    score_desafiado = models.SmallIntegerField(u'Vitórias do desafiado', validators=[MinValueValidator(0), MaxValueValidator(SCORE_VITORIA)])
    admin_validador = models.ForeignKey('jogadores.Jogador', on_delete=models.CASCADE, blank=True, null=True, related_name='admin_validador')
    data_hora = DateTimeFieldTz(u'Data e hora do resultado')
    adicionado_por = models.ForeignKey('jogadores.Jogador', on_delete=models.CASCADE, related_name='criador_desafio')
    posicao_desafiante = models.SmallIntegerField(u'Posição do desafiante', default=0)
    posicao_desafiado = models.SmallIntegerField(u'Posição do desafiado', default=0)
    
    class Meta():
        unique_together = (('desafiante', 'data_hora'), ('desafiado', 'data_hora'))
        ordering = ('data_hora',)
        
    def __str__(self):
        return f'{self.id}: {self.data_hora}'
    
    @staticmethod
    def alterar_limite_posicoes_desafio():
        DesafioLadder.LIMITE_POSICOES_DESAFIO = ConfiguracaoLadder.buscar_configuracao([ConfiguracaoLadder.CONFIGURACAO_LIMITE_POSICOES_DESAFIO,]) \
            [ConfiguracaoLadder.CONFIGURACAO_LIMITE_POSICOES_DESAFIO]
        
        # Atualizar mensagem
        DesafioLadder.MENSAGEM_ERRO_DESAFIANTE_MUITO_ABAIXO_DESAFIADO = f'Desafiante está mais de {DesafioLadder.LIMITE_POSICOES_DESAFIO} ' \
            'posições abaixo do desafiado'
            
    @staticmethod
    def alterar_melhor_de():
        DesafioLadder.MELHOR_DE = ConfiguracaoLadder.buscar_configuracao([ConfiguracaoLadder.CONFIGURACAO_MELHOR_DE,]) \
            [ConfiguracaoLadder.CONFIGURACAO_MELHOR_DE]
        
        DesafioLadder.SCORE_VITORIA = ((DesafioLadder.MELHOR_DE // 2) + 1)
        
    @staticmethod
    def alterar_uso_coringa():
        DesafioLadder.USO_CORINGA = ConfiguracaoLadder.buscar_configuracao([ConfiguracaoLadder.CONFIGURACAO_USO_CORINGA,]) \
            [ConfiguracaoLadder.CONFIGURACAO_USO_CORINGA]
        
    @property
    def lutas(self):
        """Lista de lutas que compõe o desafio"""
        return [luta_ladder.luta for luta_ladder in self.lutaladder_set.all().select_related('luta__ganhador')]
    
    def is_cancelado(self):
        """Define se é um desafio cancelado"""
        return hasattr(self, 'cancelamentodesafioladder')
    
    def is_historico(self):
        """Define se é histórico"""
        horario_atual = timezone.localtime()
        return self.data_hora.month != horario_atual.month or self.data_hora.year != horario_atual.year
        
    def is_validado(self):
        return self.admin_validador_id != None
    
    @property
    def mes_ano_ladder(self):
        """Retorna mes e ano de ladder da qual desafio faz parte"""
        if self.is_historico():
            return (self.data_hora.month, self.data_hora.year)
        return (None, None)
    
    @property
    def ladder(self):
        """Ladder a qual desafio se refere"""
        if self.is_historico():
            mes, ano = self.mes_ano_ladder
            return HistoricoLadder.objects.filter(ano=ano, mes=mes)
        return PosicaoLadder.objects
    
    def cancelavel_por_jogador(self, jogador):
        """Determina se jogador pode cancelar desafio"""
        if self.is_cancelado():
            return False
        # Admin sempre pode cancelar, criador apenas se não validado
        return jogador.admin or (not self.is_validado() and jogador == self.adicionado_por)
    
    def editavel_por_jogador(self, jogador):
        """Determinar se jogador pode editar desafio"""
        if self.is_cancelado():
            return False
        # Contanto que não esteja validado, jogador precisa ser admin ou criador
        return not self.is_validado() and (jogador.admin or jogador == self.adicionado_por)
    
    def desafiante_venceu(self):
        """Retorna se desafiante foi o ganhador"""
        return self.score_desafiante > self.score_desafiado
    
    def fora_da_season(self):
        """Retorna se desafio é de Season anterior"""
        season_atual = Season.objects.order_by('-data_inicio')[0]
        return self.data_hora < season_atual.data_hora_inicio
    
    class DesafioLadderManager(models.Manager):
        """Override do manager padrão"""
        def na_season(self, season):
            data_hora_inicio = datetime.datetime(season.data_inicio.year, season.data_inicio.month, season.data_inicio.day)
            
            # Se possui data de fim
            if season.data_fim:
                data_hora_fim = datetime.datetime(season.data_fim.year, season.data_fim.month, season.data_fim.day) \
                    + datetime.timedelta(days=1)
                return self.get_queryset().filter(data_hora__range=[timezone.make_aware(data_hora_inicio), 
                                                                timezone.make_aware(data_hora_fim, 
                                                                                    timezone.get_current_timezone())])
            else:
                # Se não, buscar apenas a partir da data inicial
                return self.get_queryset().filter(data_hora__gte=timezone.make_aware(data_hora_inicio))
    # Managers
    class DesafiosValidadosManager(models.Manager):
        """Manager para trazer desafios validados e não cancelados"""
        def get_queryset(self):
            return super().get_queryset().filter(cancelamentodesafioladder__isnull=True, admin_validador__isnull=False)
        
        def na_season(self, season):
            # Se possui data de fim
            if season.data_fim:
                data_hora_fim = datetime.datetime(season.data_fim.year, season.data_fim.month, season.data_fim.day) \
                    + datetime.timedelta(days=1)
                return self.get_queryset().filter(data_hora__range=[season.data_hora_inicio, 
                                                                timezone.make_aware(data_hora_fim)])
            else:
                # Se não, buscar apenas a partir da data inicial
                return self.get_queryset().filter(data_hora__gte=season.data_hora_inicio)
        
#     objects = models.Manager()
    objects = DesafioLadderManager()
    validados = DesafiosValidadosManager()
    
class LutaLadder(models.Model):
    """Lutas para um desafio de ladder"""
    desafio_ladder = models.ForeignKey('DesafioLadder', on_delete=models.CASCADE)
    luta = models.OneToOneField('Luta', on_delete=models.CASCADE)

templates/ladder/adicionar_permissao_aumento_range.html
{% extends 'base.html' %}

{% block title %}- Adicionar permissão de aumento de range{% endblock %}

{% block page_header %}Permissão de aumento de range{% endblock %}

{% block extra_header %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}
	<form class="col-12" action="{% url 'ladder:add_permissao_aumento_range' %}" method="post">
	    {% csrf_token %}
	    
	    {% include "form.html" with form=form_permissao_aumento_range %}
	    
	  	<input class="btn btn-lg btn-dark mt-4" type="submit" name="salvar" value="Salvar">
	</form>
{% endblock %}

{% block extra_scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){
	$('select').select2();
});
</script>
{% endblock %}

templates/ladder/analises.html
{% extends 'base.html' %}

{% block title %}- Análises{% endblock %}

{% block page_header %}Análises{% endblock %}


{% block content %}
	<div class="col-12 text-center mb-3">
		<h4>Recomendável ver em dispositivos com telas maiores</h4>
	</div>
	
	<div class="col-12 col-md-12 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Vitórias por personagem
		  	</div>
		  	<div class="card-body col-12" id="cardGrafVitoriasPorPersonagem">
		  		<div id="grafVitoriasPorPersonagem"></div>
			</div>
		</div>
	</div>
	
	<div class="col-12 col-md-12 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Quantidade/Resultado de desafios por posição
		  	</div>
		  	<div class="card-body col-12" id="cardGrafResultadosPorPosicao">
		  		<div id="grafResultadosPorPosicao"></div>
			</div>
		</div>
	</div>	
	
	<div class="col-12 col-md-12 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Resultado acumulado de desafios entre jogadores
		  	</div>
		  	<div class="card-body col-12" id="cardGrafAcumJogadores">
		  		<div class="col-12 text-center mb-0">
		  			<h4><span id="mes"></span> / <span id="ano"></span></h4>
		  		</div>
		  		<div class="col-12 text-center mb-3">
		  			<input class="btn btn-lg btn-dark mt-4" id="ant_acumulado" type="button" value="Anterior">
		  			<input class="btn btn-lg btn-dark mt-4" id="prox_acumulado" type="button" value="Próximo">
	  			</div>
	  			
	  			<div id="grafAcumJogadores"></div>
			</div>
		</div>
	</div>
	
	<div class="col-12 col-md-12 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Vitórias/derrotas por diferença de posições
		  	</div>
		  	<div class="card-body col-12" id="cardGrafResultadosDifPosicao">
		  		<div id="grafResultadosDifPosicao"></div>
			</div>
		</div>
	</div>
	
{% endblock %}

{% block extra_scripts %}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js"></script>

<script type="text/javascript">
var dataAtual = new Date();
var mes = dataAtual.getMonth() + 1;
var ano = dataAtual.getYear() + 1900;

var max_mes = mes;
var min_mes = {{ mes_inicial }};

var max_ano = ano;
var min_ano = {{ ano_inicial }};

function alterar_mes_ano() {
	$('#mes').html(mes);
	$('#ano').html(ano);
	
	if (mes == min_mes && ano == min_ano) {
		$('#ant_acumulado').addClass('disabled');
	} else if (mes == max_mes && ano == max_ano) {
		$('#prox_acumulado').addClass('disabled');
	} else {
		$('#ant_acumulado').removeClass('disabled');
		$('#prox_acumulado').removeClass('disabled');
	}
}

$(document).ready(function(){
	alterar_mes_ano();
	
	$('#prox_acumulado').click(function() {
		if ((ano == max_ano && mes < max_mes) || (ano < max_ano)) {
			mes += 1;
			if (mes == 13) {
				ano += 1;
				mes = 1;
			}
			alterar_mes_ano();
			plotGraficoAcumuladoEntreJogadores();
		}
	});
	
	$('#ant_acumulado').click(function() {
		if ((ano == min_ano && mes > min_mes) || (ano > min_ano)) {
			mes -= 1;
			if (mes == 0) {
				ano -= 1;
				mes = 12;
			}
			alterar_mes_ano();
			plotGraficoAcumuladoEntreJogadores();
		}
	});
	
	plotGraficoAcumuladoEntreJogadores();
	plotGraficoResultadosPorPosicao();
	plotGraficoVitoriasPorPersonagem();
	plotGrafResultadosDifPosicao();
});

function plotGraficoAcumuladoEntreJogadores() {
	$('#cardGrafAcumJogadores').block({ 
        message: ''
    });
    
	ajax("{% url 'ladder:analise_result_acum_jogadores' %}", 
		'GET', 
		{ano: ano, mes: mes}, 
		function(resultado) {
			var data = [
			  {
				z: resultado.resultado_desafios,
				x: resultado.jogador_enfrentado,
				y: resultado.jogador,
				hovertemplate: 'Jogador: <b>%{y}</b>' +
                        '<br>Oponente: <b>%{x}</b>' +
                        '<br>Resultado: <b>%{z:.2f}</b>',
			  	hoverinfo: 'text',
			  	name: '',
				type: 'heatmap',
				reversescale: true
			  }
			];
			
			var layout = {
			  height: 30 * resultado.jogador.length,
			  xaxis: {
			  	title: 'Oponente enfrentado'
			  }
			};
			
			Plotly.newPlot('grafAcumJogadores', data, layout);
			$('#cardGrafAcumJogadores').unblock(); 
        }
    );
}

function plotGraficoResultadosPorPosicao() {
	$('#cardGrafResultadosPorPosicao').block({ 
        message: ''
    });
    
	ajax("{% url 'ladder:analise_resultado_por_posicao' %}", 
		'GET', 
		{}, 
		function(resultado) {
			// Adicionar texto para cada ponto no gráfico
			resultado.texto = [];
			
			// Formatar quantidade de desafios
			var maior_qtd_desafios = Math.max.apply(Math, resultado.qtd_desafios);
			var tamanho_max = 25;
			for (var i = 0; i < resultado.qtd_desafios.length; i++) {
				resultado.texto.push('Desafiante: <b>' + resultado.posicao_desafiante[i] + '</b>' +
                        '<br>Desafiado: <b>' + resultado.posicao_desafiado[i] + '</b>' +
                        '<br>Média: <b>' + resultado.resultado[i].toFixed(2) + '</b>' +
                        '<br>Qtd. desafios: <b>' + resultado.qtd_desafios[i] + '</b>');
				resultado.qtd_desafios[i] = resultado.qtd_desafios[i] / maior_qtd_desafios * tamanho_max;
			}
			
			var data = [
			  {
			  	marker: {
					size: resultado.qtd_desafios,
					color: resultado.resultado,
					sizemin: 5,
					colorscale: 'RdBu',
					showscale: true,
					reversescale: true
				},
				x: resultado.posicao_desafiante,
				y: resultado.posicao_desafiado,
				text: resultado.texto,
			  	hoverinfo: 'text',
			  	name: '',
				mode: 'markers',
				type: 'scatter'
			  }
			];
			
			var layout = {
			  hovermode: 'closest',
			  height: 10 * resultado.posicao_desafiado.length,
			  xaxis: {
			  	title: 'Posição do desafiante'
			  },
			  yaxis: {
			  	title: 'Posição do desafiado'
			  }
			};
			
			Plotly.newPlot('grafResultadosPorPosicao', data, layout);
			$('#cardGrafResultadosPorPosicao').unblock(); 
        }
    );
}

function plotGraficoVitoriasPorPersonagem() {
	$('#cardGrafVitoriasPorPersonagem').block({ 
        message: ''
    });
    
	ajax("{% url 'ladder:analise_vitorias_por_personagem' %}", 
		'GET', 
		{}, 
		function(resultado) {
			var data = [
			  {
			    opacity: 0.7,
				x: resultado.personagem,
				y: resultado.qtd_lutas,
				hovertemplate: 'Lutas: <b>%{y}</b>',
			  	hoverinfo: 'text',
			  	name: '',
				type: 'bar',
				yaxys: 'y',
				offsetgroup: 1
			  },
			  {
			    opacity: 0.7,
				x: resultado.personagem,
				y: resultado.perc_vitorias,
				hovertemplate: 'Vitórias: <b>%{y:.2f}%</b>',
			  	hoverinfo: 'text',
			  	name: '',
				type: 'bar',
  				yaxis: 'y2',
				offsetgroup: 2
			  }
			];
			
			var layout = {
			  showlegend: false,
			  xaxis: {
			  	title: 'Personagem'
			  },
			  yaxis: {
			  	title: 'Qtd. lutas'
			  },
			  yaxis2: {
			    range: [0, 100],
			  	title: '% Vitórias',
			  	overlaying: 'y',
			  	side: 'right'
			  }
			};
			
			Plotly.newPlot('grafVitoriasPorPersonagem', data, layout);
			$('#cardGrafVitoriasPorPersonagem').unblock(); 
        }
    );
}

function plotGrafResultadosDifPosicao() {
	$('#cardGrafResultadosDifPosicao').block({ 
        message: ''
    });
    
	ajax("{% url 'ladder:analise_resultado_por_diferenca_posicao' %}", 
		'GET', 
		{}, 
		function(resultado) {
			var data = [
			  {
				x: resultado.dif_posicao,
				y: resultado.qtd_vitorias,
				hovertemplate: 'Diferença: <b>%{x}</b><br>Vitórias: <b>%{y}</b>',
				marker: {color: '#1f77b4'},
			  	hoverinfo: 'text',
			  	name: '',
				type: 'bar'
			  },
			  {
				x: resultado.dif_posicao,
				y: resultado.qtd_derrotas,
				hovertemplate: 'Diferença: <b>%{x}</b><br>Derrotas: <b>%{y}</b>',
				marker: {color: '#d62728'},
			  	hoverinfo: 'text',
			  	name: '',
				type: 'bar',
				xaxis: 'x2',
				yaxis: 'y2'
			  },
			  {
			  	x: resultado.dif_posicao,
			  	y: resultado.perc_vitorias,
				hovertemplate: '% Vitórias: <b>%{y:.2f}</b>',
				marker: {color: '#1f77b4'},
			  	hoverinfo: 'text',
			  	name: '',
				type: 'bar',
				xaxis: 'x3',
				yaxis: 'y3'
			  },
			  {
			  	x: resultado.dif_posicao,
			  	y: resultado.perc_derrotas,
				hovertemplate: '% Derrotas: <b>%{y:.2f}</b>',
				marker: {color: '#d62728'},
			  	hoverinfo: 'text',
			  	name: '',
				type: 'bar',
				xaxis: 'x3',
				yaxis: 'y3'
			  }
			];
			
			var layout = {
			  showlegend: false,
			  yaxis: {
			  	title: 'Qtd. Vitórias'
		  	  },
			  xaxis2: {
			  	title: 'Diferença de posições'
			  },
			  yaxis2: {
			  	title: 'Qtd. Derrotas'
		  	  },
			  yaxis3: {
			  	title: 'Percentuais'
			  },
			  grid: {rows: 1, columns: 3, pattern: 'independent'},
			  barmode: 'stack'
			};
			
			Plotly.newPlot('grafResultadosDifPosicao', data, layout);
			$('#cardGrafResultadosDifPosicao').unblock(); 
        }
    );
}
</script>
{% endblock %}