ladder/urls.py
from django.urls import path

from ladder import views

app_name='ladder'
urlpatterns = [
    # Ladder
    path(r'atual/', views.detalhar_ladder_atual, name='detalhar_ladder_atual'),
    path(r'hall-fama/<int:ano>/<int:indice>/', views.detalhar_hall_fama, name='detalhar_hall_fama'),
    path(r'historico/<int:ano>/<int:mes>/', views.detalhar_ladder_historico, name='detalhar_ladder_historico'),
    path(r'hall-fama/listar/', views.listar_hall_fama, name='listar_hall_fama'),
    path(r'historico/listar/', views.listar_ladder_historico, name='listar_ladder_historico'),
    path(r'atual/listar-desafios/', views.listar_desafios_ladder, name='listar_desafios_ladder_atual'),
    path(r'historico/<int:ano>/<int:mes>/listar-desafios/', views.listar_desafios_ladder, name='listar_desafios_ladder_historico'),
    path(r'hall-fama/<int:ano>/<int:indice>/listar-desafios/', views.listar_desafios_season, name='listar_desafios_season'),
    
    # Remoções
    path(r'cancelar-remocao/<int:remocao_id>/', views.cancelar_remocao_jogador_ladder, name='cancelar_remocao_jogador_ladder'),
    path(r'listar-remocoes/', views.listar_remocoes_jogador_ladder, name='listar_remocoes_jogador_ladder'),
    path(r'remover-jogador/', views.remover_jogador_ladder, name='remover_jogador_ladder'),
    
    # Permissões de aumento de range
    path(r'permissao-aumento-range/adicionar/', views.add_permissao_aumento_range, name='add_permissao_aumento_range'),
    path(r'permissao-aumento-range/remover/', views.remover_permissao_aumento_range, name='remover_permissao_aumento_range'),
    path(r'permissao-aumento-range/remover/<int:permissao_id>/', views.remover_permissao_aumento_range, name='remover_permissao_aumento_range'),
    
    # Desafios de ladder
    path(r'desafio/adicionar/', views.add_desafio_ladder, name='adicionar_desafio_ladder'),
    path(r'desafio/cancelar/<int:desafio_id>/', views.cancelar_desafio_ladder, name='cancelar_desafio_ladder'),
    path(r'desafio/detalhar/<int:desafio_id>/', views.detalhar_desafio_ladder, name='detalhar_desafio_ladder'),
    path(r'desafio/editar/<int:desafio_id>/', views.editar_desafio_ladder, name='editar_desafio_ladder'),
    path(r'desafio/listar-pendentes/', views.listar_desafios_ladder_pendentes_validacao, name='listar_desafios_ladder_pendentes_validacao'),
    path(r'desafio/validar/<int:desafio_id>/', views.validar_desafio_ladder, name='validar_desafio_ladder'),
    
    # Regras
    path(r'regras/', views.detalhar_regras, name='detalhar_regras_ladder'),
    
    # Lutas
    path(r'lutas/detalhar/<int:luta_id>/', views.detalhar_luta, name='detalhar_luta'),
    
    # Análises
    path('analises/geral/', views.analises, name='analises'),
    path('analises/geral/resultado-acumulado-jogadores/', views.analise_resultado_acumulado_jogadores, name='analise_result_acum_jogadores'),
    path('analises/geral/resultado-posicao/', views.analise_resultado_por_posicao, name='analise_resultado_por_posicao'),
    path('analises/geral/resultado-diferenca-posicao/', views.analise_resultado_por_diferenca_posicao, name='analise_resultado_por_diferenca_posicao'),
    path('analises/geral/vitorias-por-personagem/', views.analise_vitorias_por_personagem, name='analise_vitorias_por_personagem'),
    path('analises/jogador/', views.analises_por_jogador, name='analises_por_jogador'),
    path('analises/jogador/resultado-acumulado-jogador/', views.analise_resultado_acumulado_para_um_jogador, name='analise_result_acum_jogador'),
    path('analises/jogador/resultado-contra-personagens-jogador/', views.analise_resultado_acumulado_contra_personagens_para_um_jogador, 
         name='analise_result_jogador_contra_personagens'),
    path('analises/jogador/resultado-stages-jogador/', views.analise_resultado_stages_para_um_jogador, name='analise_stages_jogador'),
    path('analises/jogador/vitorias-desafio/', views.analise_vitorias_desafio_para_um_jogador, name='analise_vitorias_desafio_jogador'),
]

smashLadder/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls.conf import re_path
from django.views.defaults import page_not_found

from ladder.models import Lockdown
from smashLadder import views, settings


urlpatterns = []

# Verificar lockdown de seasons
try:
    if Lockdown.sistema_em_lockdown():
        urlpatterns.append(re_path(r'.*?', page_not_found, {'exception': Exception('Gerando nova Season')}))
except:
    pass
        
urlpatterns.extend([
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', views.home, name='inicio'),
    
    path('jogadores/', include('jogadores.urls.urls_jogadores')),
    path('ladder/', include('ladder.urls')),
    path('personagens/', include('jogadores.urls.urls_personagens')),
    path('stages/', include('jogadores.urls.urls_stages')),
    path('torneios/', include('torneios.urls')),
    path('treinamento/', include('treinamento.urls')),
])

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

treinamento/urls.py
"""
Configuração de URL para treinamento
"""
from django.urls import path

from treinamento import views


app_name='treinamento'
urlpatterns = [
    path(r'', views.painel_treinamento, name='painel_treinamento'),
    
    # Registros de treinamento
    path(r'registro/<int:registro_id>/adicionar-resultado/', views.add_resultado_treinamento, name='add_resultado_treinamento'),
    path(r'registro/<int:registro_id>/apagar/', views.apagar_registro_treinamento, name='apagar_registro_treinamento'),
    path(r'registro/<int:registro_id>/detalhar/', views.detalhar_registro_treinamento, name='detalhar_registro_treinamento'),
    path(r'registro/<int:registro_id>/editar/', views.editar_registro_treinamento, name='editar_registro_treinamento'),
    path(r'registro/adicionar/', views.add_registro_treinamento, name='add_registro_treinamento'),
    path(r'registro/listar/', views.listar_registros_treinamento, name='listar_registros_treinamento'),
    
    # Anotações
    path(r'anotacao/adicionar/', views.add_anotacao, name='add_anotacao'),
    path(r'anotacao/<int:anotacao_id>/apagar/', views.apagar_anotacao, name='apagar_anotacao'),
    path(r'anotacao/listar/', views.listar_anotacoes, name='listar_anotacoes'),
    
    # Anotações
    path(r'link-util/adicionar/', views.add_link_util, name='add_link_util'),
    path(r'link-util/<int:link_util_id>/apagar/', views.apagar_link_util, name='apagar_link_util'),
    path(r'link-util/listar/', views.listar_links_uteis, name='listar_links_uteis'),
    
    # Métricas
    path(r'metrica/adicionar/', views.add_metrica, name='add_metrica'),
    path(r'metrica/<int:metrica_id>/apagar/', views.apagar_metrica, name='apagar_metrica'),
    path(r'metrica/<int:metrica_id>/detalhar/', views.detalhar_metrica, name='detalhar_metrica'),
    path(r'metrica/<int:metrica_id>/editar/', views.editar_metrica, name='editar_metrica'),
    path(r'metrica/listar/', views.listar_metricas, name='listar_metricas'),
    
]

treinamento/views.py
# -*- coding: utf-8 -*-
"""Views para treinamento"""
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models.aggregates import Sum
from django.db.models.expressions import ExpressionWrapper, F
from django.db.models.fields import DurationField
from django.shortcuts import render, get_object_or_404, redirect
from django.urls.base import reverse
from django.utils import timezone

from treinamento.forms import RegistroTreinamentoForm, AnotacaoForm, MetricaForm, \
    ResultadoTreinamentoForm, LinkUtilForm
from treinamento.models import RegistroTreinamento, Anotacao, Metrica, \
    ResultadoTreinamento, LinkUtil
from treinamento.utils import converter_segundos_duracao


@login_required
def add_anotacao(request):
    """Adiciona uma anotação"""
    jogador = request.user.jogador
    
    if request.POST:
        form_anotacao = AnotacaoForm(request.POST)
        
        if form_anotacao.is_valid():
            try:
                with transaction.atomic():
                    anotacao = form_anotacao.save(commit=False)
                    
                    # Adicionar jogador
                    anotacao.jogador = jogador
                    anotacao.save()
                        
                    messages.success(request, 'Anotação adicionada com sucesso')
                    return redirect(reverse('treinamento:listar_anotacoes'))
                
            except Exception as e:
                messages.error(request, e)
        
        else:
            for erro in form_anotacao.non_field_errors():
                messages.error(request, erro)
                
    else:
        form_anotacao = AnotacaoForm()
        
    return render(request, 'treinamento/adicionar_anotacao.html', {'form_anotacao': form_anotacao})

@login_required
def apagar_anotacao(request, anotacao_id):
    """Apaga uma anotação"""
    jogador = request.user.jogador
    
    anotacao = get_object_or_404(Anotacao, jogador=jogador, id=anotacao_id)
    
    if request.POST:
        try:
            with transaction.atomic():
                anotacao.delete()
                
                messages.success(request, 'Anotação apagada com sucesso')
                return redirect(reverse('treinamento:listar_anotacoes'))
            
        except Exception as e:
            messages.error(request, e)
        
    return render(request, 'treinamento/apagar_anotacao.html', {'anotacao': anotacao})

@login_required
def listar_anotacoes(request):
    """Lista anotações de um jogador"""
    anotacoes = Anotacao.objects.filter(jogador=request.user.jogador)
    
    return render(request, 'treinamento/listar_anotacoes.html', {'anotacoes': anotacoes})
    
@login_required
def add_link_util(request):
    """Adiciona uma link útil"""
    jogador = request.user.jogador
    
    if request.POST:
        form_link_util = LinkUtilForm(request.POST)
        
        if form_link_util.is_valid():
            try:
                with transaction.atomic():
                    link_util = form_link_util.save(commit=False)
                    
                    # Adicionar jogador
                    link_util.jogador = jogador
                    link_util.save()
                        
                    messages.success(request, 'Link útil adicionado com sucesso')
                    return redirect(reverse('treinamento:listar_links_uteis'))
                
            except Exception as e:
                messages.error(request, e)
        
        else:
            for erro in form_link_util.non_field_errors():
                messages.error(request, erro)
                
    else:
        form_link_util = LinkUtilForm()
        
    return render(request, 'treinamento/adicionar_link_util.html', {'form_link_util': form_link_util})

@login_required
def apagar_link_util(request, link_util_id):
    """Apaga uma link útil"""
    jogador = request.user.jogador
    
    link_util = get_object_or_404(LinkUtil, jogador=jogador, id=link_util_id)
    
    if request.POST:
        try:
            with transaction.atomic():
                link_util.delete()
                
                messages.success(request, 'Link útil apagado com sucesso')
                return redirect(reverse('treinamento:listar_links_uteis'))
            
        except Exception as e:
            messages.error(request, e)
        
    return render(request, 'treinamento/apagar_link_util.html', {'link_util': link_util})

@login_required
def listar_links_uteis(request):
    """Lista links úteis de um jogador"""
    links_uteis = LinkUtil.objects.filter(jogador=request.user.jogador)
    
    return render(request, 'treinamento/listar_links_uteis.html', {'links_uteis': links_uteis})

@login_required
def add_metrica(request):
    """Adiciona uma métrica"""
    jogador = request.user.jogador
    
    if request.POST:
        form_metrica = MetricaForm(request.POST)
        
        if form_metrica.is_valid():
            try:
                with transaction.atomic():
                    metrica = form_metrica.save(commit=False)
                    
                    # Adicionar jogador
                    metrica.jogador = jogador
                    metrica.save()
                        
                    messages.success(request, 'Métrica adicionada com sucesso')
                    return redirect(reverse('treinamento:detalhar_metrica', kwargs={'metrica_id': metrica.id}))
                
            except Exception as e:
                messages.error(request, e)
        
        else:
            for erro in form_metrica.non_field_errors():
                messages.error(request, erro)
                
    else:
        form_metrica = MetricaForm()
        
    return render(request, 'treinamento/adicionar_metrica.html', {'form_metrica': form_metrica})

@login_required
def apagar_metrica(request, metrica_id):
    """Apaga uma métrica"""
    metrica = get_object_or_404(Metrica, jogador=request.user.jogador, id=metrica_id)
    
    if request.POST:
        try:
            with transaction.atomic():
                metrica.delete()
                
                messages.success(request, 'Métrica apagada com sucesso')
                return redirect(reverse('treinamento:listar_metricas'))
            
        except Exception as e:
            messages.error(request, e)
        
    return render(request, 'treinamento/apagar_metrica.html', {'metrica': metrica})

@login_required
def detalhar_metrica(request, metrica_id):
    """Detalha uma métrica"""
    metrica = get_object_or_404(Metrica, id=metrica_id, jogador=request.user.jogador)
    resultados = list(ResultadoTreinamento.objects.filter(metrica=metrica, registro_treinamento__jogador=request.user.jogador) \
        .order_by('registro_treinamento__fim').values_list('registro_treinamento__inicio', 'quantidade'))
    
    resultados_grafico = [{'x': resultado[0].strftime('%d/%m/%Y %H:%M'), 'y': resultado[1]} for resultado in resultados]
    
    media_resultados = {}
    maior_resultado = {}
    menor_resultado = {}
    
    if resultados:
        media_resultados['geral'] = sum([resultado[1] for resultado in resultados]) / len(resultados)
        
        resultados_30_dias = [resultado for resultado in resultados if 
                                           resultado[0] >= (timezone.localtime() - datetime.timedelta(days=30))]
        media_resultados['30_dias'] = sum([resultado[1] for resultado in resultados_30_dias]) / len(resultados_30_dias)
    
        
        maior_resultado['geral'] = max([resultado[1] for resultado in resultados])
        
        maior_resultado['30_dias'] = max([resultado[1] for resultado in resultados if 
                                           resultado[0] >= (timezone.localtime() - datetime.timedelta(days=30))])
        
        
        menor_resultado['geral'] = min([resultado[1] for resultado in resultados])
        
        menor_resultado['30_dias'] = min([resultado[1] for resultado in resultados if 
                                           resultado[0] >= (timezone.localtime() - datetime.timedelta(days=30))])
    else:
        media_resultados['geral'] = 0
        media_resultados['30_dias'] = 0
        maior_resultado['geral'] = 0
        maior_resultado['30_dias'] = 0
        menor_resultado['geral'] = 0
        menor_resultado['30_dias'] = 0
    
    if len(resultados) >= 2:
        metrica.avanco = ((resultados[-1][1] / resultados[0][1]) - 1) * 100
    else:
        metrica.avanco = 0
    
    return render(request, 'treinamento/detalhar_metrica.html', {'metrica': metrica, 'resultados_grafico': resultados_grafico,
                                                                 'media_resultados': media_resultados,
                                                                 'maior_resultado': maior_resultado,
                                                                 'menor_resultado': menor_resultado})

@login_required
def editar_metrica(request, metrica_id):
    """Edita uma métrica"""
    jogador = request.user.jogador
    
    metrica = get_object_or_404(Metrica, jogador=jogador, id=metrica_id)
    
    if request.POST:
        form_metrica = MetricaForm(request.POST, instance=metrica)
        
        if form_metrica.is_valid():
            try:
                with transaction.atomic():
                    metrica = form_metrica.save(commit=False)
                    
                    # Adicionar jogador
                    metrica.jogador = jogador
                    metrica.save()
                    
                    messages.success(request, 'Métrica editada com sucesso')
                    return redirect(reverse('treinamento:detalhar_metrica', kwargs={'metrica_id': metrica.id}))
                
            except Exception as e:
                messages.error(request, e)
        
        else:

templates/treinamento/adicionar_anotacao.html
{% extends 'base.html' %}

{% block title %}- Adicionar anotação{% endblock %}

{% block page_header %}Anotação{% endblock %}

{% block content %}
	<form class="col-12" action="{% url 'treinamento:add_anotacao' %}" method="post">
	    {% csrf_token %}
	    
	    {% include "form.html" with form=form_anotacao %}
	    
	  	<input class="btn btn-lg btn-dark mt-4" type="submit" name="salvar" value="Salvar">
	</form>
{% endblock %}

templates/treinamento/adicionar_metrica.html
{% extends 'base.html' %}

{% block title %}- Adicionar métrica{% endblock %}

{% block page_header %}Métrica{% endblock %}

{% block content %}
	<form class="col-12" action="{% url 'treinamento:add_metrica' %}" method="post">
	    {% csrf_token %}
	    
	    {% include "form.html" with form=form_metrica %}
	    
	  	<input class="btn btn-lg btn-dark mt-4" type="submit" name="salvar" value="Salvar">
	</form>
{% endblock %}

templates/treinamento/adicionar_registro_treinamento.html
{% extends 'base.html' %}
{% load static %}

{% block title %}- Adicionar registro de treinamento{% endblock %}

{% block page_header %}Registro de treinamento{% endblock %}

{% block extra_header %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}
	<form class="col-12" action="{% url 'treinamento:add_registro_treinamento' %}" method="post">
	    {% csrf_token %}
	    
	    {% include "form.html" with form=form_registro_treinamento %}
	    
	  	<input class="btn btn-lg btn-dark mt-4" type="submit" name="salvar" value="Salvar">
	</form>
{% endblock %}

{% block extra_scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src={% static "jquery.mask.min.js" %} type="text/javascript"></script>

<script type="text/javascript">
$(document).ready(function(){
	$('select').select2();
	$('.data-hora').mask('00/00/0000 00:00', {placeholder: 'DD/MM/AAAA hh:mm'});
});
</script>
{% endblock %}

templates/treinamento/apagar_anotacao.html
{% extends 'base.html' %}
{% load static %}

{% block title %}- Apagar anotação{% endblock %}

{% block page_header %}Apagar anotação {{ anotacao.id }}{% endblock %}

{% block content %}
	<div class="card col-12 col-md-3">
	  	<div class="card-body">
	    	<h5 class="card-title">{{ anotacao.data_hora|date:'d/m/Y' }}</h5>
	    	
		    <h6 class="card-subtitle mb-2 text-muted">{{ anotacao.data_hora|date:'H:i' }}</h6>
		    
	    	<p class="card-text">{{ anotacao.texto }}</p>
	  	</div>
	</div>
	
	<form class="col-12" action="{% url 'treinamento:apagar_anotacao' anotacao.id %}" method="post">
	    {% csrf_token %}
	    
	  	<input class="btn btn-lg btn-dark mt-4" type="submit" name="apagar" value="Apagar">
	</form>
{% endblock %}

templates/treinamento/apagar_link_util.html
{% extends 'base.html' %}
{% load static %}

{% block title %}- Apagar link útil{% endblock %}

{% block page_header %}Apagar link útil {{ link_util.id }}{% endblock %}

{% block content %}
	<div class="card col-12 col-md-3">
	  	<div class="card-body">
	    	<h5 class="card-title">{{ link_util.data_hora|date:'d/m/Y' }}</h5>
	    	
		    <h6 class="card-subtitle mb-2 text-muted">{{ link_util.data_hora|date:'H:i' }}</h6>
		    
	    	<p class="card-text">{{ link_util.texto }}</p>
	  	</div>
	</div>
	
	<form class="col-12" action="{% url 'treinamento:apagar_link_util' link_util.id %}" method="post">
	    {% csrf_token %}
	    
	  	<input class="btn btn-lg btn-dark mt-4" type="submit" name="apagar" value="Apagar">
	</form>
{% endblock %}

templates/treinamento/detalhar_registro_treinamento.html
{% extends 'base.html' %}

{% block title %}
	- Registro de treinamento
{% endblock %}

{% block page_header %}
	Registro de treinamento
{% endblock %}

{% block content %}
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Dados
		  	</div>
		  	<div class="card-body col-12">
		  		<div class="row">
			  		<div class="col-6">
					    <h6 class="card-title">Data/hora de início</h6>
					    <h6 class="card-title"><strong>{{ registro_treinamento.inicio|date:'d/m/Y H:i' }}</strong></h6>
				    </div>
			  		<div class="col-6">
					    <h6 class="card-title">Data/hora de fim</h6>
					    <h6 class="card-title"><strong>{{ registro_treinamento.fim|date:'d/m/Y H:i' }}</strong></h6>
				    </div>
				    
			  		<div class="col-6">
					    <h6 class="card-title">Duração</h6>
					    <h6 class="card-title"><strong>{{ registro_treinamento.duracao }}</strong></h6>
				    </div>
			    </div>
			    
				<a class="card-link" href="{% url 'treinamento:apagar_registro_treinamento' registro_treinamento.id %}">Apagar</a>
				<a class="card-link" href="{% url 'treinamento:editar_registro_treinamento' registro_treinamento.id %}">Editar</a>
		  	</div>
		</div>
	</div>
	
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Resultados
		  	</div>
		  	<ul class="list-group list-group-flush">
			  	{% for resultado in resultados %}
					<li class="list-group-item">
						<span>{{ resultado.metrica.nome }}: {{ resultado.quantidade }}</span>
					</li>
				{% endfor %}
		  	</ul>
		  	<div class="card-body col-12 text-center">
				<a class="card-link" href="{% url 'treinamento:add_resultado_treinamento' registro_treinamento.id %}">Adicionar resultado</a>
		  	</div>
		</div>
	</div>
{% endblock %}

templates/treinamento/editar_metrica.html
{% extends 'base.html' %}

{% block title %}- Editar métrica{% endblock %}

{% block page_header %}Métrica {{ form_metrica.instance.id }}{% endblock %}

{% block content %}
	<form class="col-12" action="{% url 'treinamento:editar_metrica' form_metrica.instance.id %}" method="post">
	    {% csrf_token %}
	    
	    {% include "form.html" with form=form_metrica %}
	    
	  	<input class="btn btn-lg btn-dark mt-4" type="submit" name="salvar" value="Salvar">
	</form>
{% endblock %}

templates/treinamento/painel.html
{% extends 'base.html' %}

{% block title %}
	- Painel de treinamento
{% endblock %}

{% block page_header %}
	Painel de treinamento
{% endblock %}

{% block content %}
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Links úteis
		  	</div>
		  	<ul class="list-group list-group-flush">
			  	{% for link_util in links_uteis %}
					<li class="list-group-item">
						<a href="{{ link_util.url }}">{{ link_util.nome }}</a>
					</li>
				{% endfor %}
		  	</ul>
		  	<div class="card-body col-12 text-center">
				<a class="card-link" href="{% url 'treinamento:add_link_util' %}">Adicionar link útil</a>
		  	</div>
		  	<div class="card-body col-12 text-center">
				<a class="card-link" href="{% url 'treinamento:listar_links_uteis' %}">Ver todos</a>
		  	</div>
		</div>
	</div>
	
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Registros de treinamento
		  	</div>
		  	<ul class="list-group list-group-flush">
			  	{% for registro in ultimos_registros %}
					<li class="list-group-item">
						<span><a href="{% url 'treinamento:detalhar_registro_treinamento' registro.id %}">{{ registro.inicio|date:'d/m/Y' }}</a></span>
					</li>
				{% endfor %}
		  	</ul>
		  	<div class="card-body col-12 text-center">
				<a class="card-link" href="{% url 'treinamento:add_registro_treinamento' %}">Adicionar registro</a>
		  	</div>
		  	<div class="card-body col-12 text-center">
				<a class="card-link" href="{% url 'treinamento:listar_registros_treinamento' %}">Ver todos</a>
		  	</div>
		</div>
	</div>
	
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Métricas
		  	</div>
		  	<ul class="list-group list-group-flush">
			  	{% for metrica in metricas %}
					<li class="list-group-item">
						<span><a href="{% url 'treinamento:detalhar_metrica' metrica.id %}">{{ metrica.nome }}</a></span>
					</li>
				{% endfor %}
		  	</ul>
		  	<div class="card-body col-12 text-center">
				<a class="card-link" href="{% url 'treinamento:add_metrica' %}">Adicionar métrica</a>
		  	</div>
		  	<div class="card-body col-12 text-center">
				<a class="card-link" href="{% url 'treinamento:listar_metricas' %}">Ver todas</a>
		  	</div>
		</div>
	</div>
	
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Anotações
		  	</div>
		  	<ul class="list-group list-group-flush">
			  	{% for anotacao in ultimas_anotacoes %}
					<li class="list-group-item">
						<span>{{ anotacao.texto }}</span>
					</li>
				{% endfor %}
		  	</ul>
		  	<div class="card-body col-12 text-center">
				<a class="card-link" href="{% url 'treinamento:add_anotacao' %}">Adicionar anotação</a>
		  	</div>
		  	<div class="card-body col-12 text-center">
				<a class="card-link" href="{% url 'treinamento:listar_anotacoes' %}">Ver todas</a>
		  	</div>
		</div>
	</div>
	
	<div class="col-12 col-md-4 my-2">
		<div class="card">
		  	<div class="card-header bg-cinza-2">
		    	Dados
		  	</div>
		  	<div class="card-body col-12">
		  		<div class="row">
			  		<div class="col-6">
					    <h6 class="card-title">Anotações</h6>
					    <h6 class="card-title"><strong>{{ dados_treinamento.qtd_anotacoes }}</strong></h6>
				    </div>
			  		<div class="col-6">
					    <h6 class="card-title">Métricas</h6>
					    <h6 class="card-title"><strong>{{ dados_treinamento.qtd_metricas }}</strong></h6>
				    </div>
				    
			  		<div class="col-6">
					    <h6 class="card-title">Registros de treinamento</h6>
					    <h6 class="card-title"><strong>{{ dados_treinamento.qtd_sessoes_treinamento }}</strong></h6>
				    </div>
			  		<div class="col-6">
					    <h6 class="card-title">Duração total</h6>
					    <h6 class="card-title"><strong>{{ dados_treinamento.tempo_registrado }}</strong></h6>
				    </div>
				    
			  		<div class="col-6">
					    <h6 class="card-title">Resultados cadastrados</h6>
					    <h6 class="card-title"><strong>{{ dados_treinamento.qtd_resultados }}</strong></h6>
				    </div>
			    </div>
		  	</div>
		</div>
	</div>
{% endblock %}